AWSTemplateFormatVersion: '2010-09-09'

Resources:
  SongsDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: core_pepper
      PubliclyAccessible: true
      StorageType: gp2
      MasterUsername: postgres
      MasterUserPassword: db_password
      Engine: mysql
      EngineVersion: 15.3
